### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp-apic-operator#21]
│ reduce the verbosity of these warnings, use the -compact-warnings option.
╵
╷
│ Warning: Values for undeclared variables
│ 
│ In addition to the other similar warnings shown, 5 other variable(s)
│ defined without being declared.
╵
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 33:
│   33: variable "cluster_type" {
│ 
│ The root module input variable "cluster_type" is not set, and has no
│ default value. Use a -var or -var-file command line argument to provide a
│ value for this variable.
╵
Error: Process completed with exit code 1.

**Comment by seansund** [comment]
Provide a default value for cluster_type

**Comment by seansund** [comment]
The error on this one is actually different than what has been listed. Here is the error from the log -

```
│ Error: Reference to undeclared module
│ 
│   on stage1-gitops.tf line 40, in module "gitea":
│   40:   olm_namespace = module.dev_software_olm.olm_namespace
│ 
│ No module call named "dev_software_olm" is declared in the root module.
╵
╷
│ Error: Reference to undeclared module
│ 
│   on stage1-gitops.tf line 41, in module "gitea":
│   41:   operator_namespace = module.dev_software_olm.target_namespace
│ 
│ No module call named "dev_software_olm" is declared in the root module.
╵
╷
│ Error: Reference to undeclared module
│ 
│   on module/stage1-olm.tf line 4, in module "dev_software_olm":
│    4:     cluster_config_file = module.dev_cluster.config_file_path
│ 
│ No module call named "dev_cluster" is declared in module.apic.
╵
```

That happened because you didn't copy the `olm` test stage into the module from step 10 of the instructions - https://ibm.ent.box.com/notes/1009912545692?s=q5s5jwsd8b37k9tbzt73hkmo4tb2tbb8

**Comment by balasgit** [comment]
Fix all the issues except this one coming

More Details - https://github.com/cloud-native-toolkit/terraform-gitops-cp-apic-operator/actions/runs/3139219392

╷
│ Warning: Value for undeclared variable
│ Error: Reference to undeclared module
│ 
│ 
│ The root module does not declare a variable named "user_access_group" but a
│   on module/stage1-olm.tf line 4, in module "dev_software_olm":
│ value was found in file "terraform.tfvars". If you meant to use this value,
│    4:     cluster_config_file = module.dev_cluster.config_file_path
│ add a "variable" block to the configuration.
│ 
│ 
│ No module call named "dev_cluster" is declared in module.apic.
│ To silence these warnings, use TF_VAR_... environment variables to provide
╵
│ certain "global" settings to all configurations in your organization. To
│ reduce the verbosity of these warnings, use the -compact-warnings option.
╵
╷
│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named "access_group_provision"
│ but a value was found in file "terraform.tfvars". If you meant to use this
│ value, add a "variable" block to the configuration.
│ 
│ To silence these warnings, use TF_VAR_... environment variables to provide
│ certain "global" settings to all configurations in your organization. To
│ reduce the verbosity of these warnings, use the -compact-warnings option.
╵
╷
│ Warning: Values for undeclared variables
│ 
│ In addition to the other similar warnings shown, 5 other variable(s)
│ defined without being declared.
╵
╷
│ Warning: Attribute Deprecated
│ 
│   with module.dev_cluster.module.setup_clis.random_string.uuid,
│   on .terraform/modules/dev_cluster.setup_clis/main.tf line 15, in resource "random_string" "uuid":
│   15:   number  = false
│ 
│ **NOTE**: This is deprecated, use `numeric` instead.
│ 
│ (and 2 more similar warnings elsewhere)
╵
Error: Process completed with exit code 1.

**Comment by balasgit** [comment]
Module exist in the stage. This is one of weird issues in couple of modules 

│ 
│ (and 2 more similar warnings elsewhere)
╵
│ Error: Reference to undeclared module
│ 
│   on module/stage1-olm.tf line 4, in module "dev_software_olm":
│    4:     cluster_config_file = module.dev_cluster.config_file_path
│ 
│ No module call named "dev_cluster" is declared in module.apic.
